try {
    console.log(x)  
}
catch (err) {
    console.log("I am catch block") 
}
finally {
    console.log("I am finally block")
}